config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions],
    controllers: { omniauth_callbacks: 'omniauth_callbacks',
                   registrations: 'registrations'}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

  # root :to => 'high_voltage/pages#show', :id => 'home'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  get '/:id', to: 'profiles#show', as: :profile

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by(profile_name: params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: Rails.root.join('public', '404.html'), status: 404, formats: [:html], layout: false
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<%= page_header do %>
  <h1>
    <% if @user.avatar.attached? %>
      <%= image_tag(@user.avatar.variant(:thumb), alt: @user.full_name, class: "img-polaroid") %>
    <% else %>
      <%= avatar_profile_link @user, {}, class: '' %>
    <% end %>
    <%= @user.full_name %>
  </h1>
<% end %>

<%= link_to "Albums", albums_path(@user), class: 'btn' %>

<% if signed_in? %>
  <span id="friend-status">
    <% if current_user == @user %>
    <% elsif current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
      <%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'btn btn-primary' %>
    <% else %>
      <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn btn-primary', id: 'add-friendship', data: { friend_id: @user.to_param} %>
  <% end %>
  </span>
<% end %>

<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well">
      <%= status.content %>
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
  <% end %>
<% end %>