config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions],
    controllers: { omniauth_callbacks: 'omniauth_callbacks',
                   registrations: 'registrations'}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

  # root :to => 'high_voltage/pages#show', :id => 'home'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  get '/:id', to: 'profiles#show', as: :profile

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  def index
    params[:page] ||=1
    if user_signed_in?
      @statuses = Status.where.not(user: current_user.blocked_friends).
        order('created_at desc').
        paginate(:page => params[:page]).includes(:user, :document)
    else
      @statuses = Status.order('created_at desc').
        paginate(:page => params[:page]).includes(:user, :document)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  def new
    @status = current_user.statuses.new
    @status.build_document

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        current_user.create_activity(@status, 'created')
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    status = current_user.statuses.find(params[:id])
    document = status.document

    status.transaction do
      status.update!(status_params)
      document.update!(document_params) if document
      current_user.create_activity(status, 'updated')
    end

    respond_to do |format|
      redirect_url  = status_path(status)
      format.html { redirect_to redirect_url, :only_path => true , notice: 'Status was successfully updated.' }
      format.json { render :show, status: :ok, location: status }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.html  do
        flash.now[:error] = "Update failed."
        render action: "edit"
      end
      format.json { render json: status.errors, status: :unprocessable_entity }
    end
  end

  def destroy
    @status = Status.find(params[:id])
    @status.destroy
    current_user.create_activity(@status, 'deleted')
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_status
    @status = Status.find(params.require(:id))
  end

  def status_params
    params.require(:status).permit(:content, :attachment,  document_attributes: [:attachment, :remove_attachment] ) if params[:status]
  end

  def document_params
    params.permit(document_attributes: :attachment)
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: { class: 'form-horizontal', multipart: true }, wrapper: :horizontal_form) do |f| %>
  <% if @status.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@status.errors.count, 'error') %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class='form-group'>
      <label class='col-sm-2 control-label'>Content</label>
      <div class='col-sm-10'>
        <%= f.input :content, label: false, class: 'form-control' %>
      </div>
    </div>
    <%= f.fields_for :document do |document_fields| %>
    <% if document_fields.object.attachment.attached? %>
      <div class='form-group'>
        <label class='col-sm-2 control-label'>Current attachment</label>
        <div class='controls col-sm-10'>
          <%= link_to document_fields.object.attachment.filename, url_for(document_fields.object.attachment) %>
        </div>
      </div>
      <div class='text-center'>
        <%= image_tag(@status.user.avatar.variant(:large), alt: @status.user.full_name, class: 'img-responsive') if @status.user.avatar.attached? %>
      </div>
      <div class='form-group'>
        <div class='col-sm-7'>
          <div class='checkbox'>
            <label>
              <%= document_fields.input :remove_attachment, as: :boolean, label: false %><strong>Remove Attachments?</strong>
            </label>
          </div>
        </div>
      </div>
    <% end %>
    <div class='form-group'>
      <label class='col-sm-2 control-label'>Attachment</label>
      <div class='col-sm-3'>
        <%= document_fields.input :attachment, as: :file, label: false %>
      </div>
    </div>
  <% end %>

  <div class='form-actions'>
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Back', statuses_path, class: 'btn btn-info' %>
  </div>
<% end %>
<br/>

app/views/statuses/edit.html.erb
<%= page_header do %>
  <h1>Edit Status</h1>
<% end %>

<%= render 'form' %>

app/views/statuses/index.html.erb
<div class="page-header">
	<h1>All of the Statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
  <% if can_display_status?(status) %>
    <div class="status media">
      <% if status.user.avatar.attached? %>
        <%= link_to(image_tag(status.user.avatar.variant(:thumb),
                              alt: status.user.profile_name,
                              class: 'pull-left avatar'),
                              profile_path(status.user)) %>
      <% else %>
        <%= avatar_profile_link status.user, {alt: status.user.profile_name}, class: 'pull-left gravatar' %>
      <% end %>
      <div class="media-body">
        <h4 class="media-heading"><%= status.user.full_name %></h4>
        <p>
          <%= status.content %>
          <% if status.document&.attachment&.attached? %>
            <%= image_tag(status.document.attachment.variant(:thumb), class: "img-polaroid") %>
          <% end %>
        </p>
        <div class="meta">
            <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
            <% if signed_in? && current_user == status.user %>
              <span class="admin">
                | <%= link_to "Edit", edit_status_path(status) %> |
                <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
              </span>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<%= will_paginate @statuses %>

app/views/statuses/new.html.erb
<%= page_header do %>
  <h1>New Status Update</h1>
<% end %>

<%= render 'form' %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span8 offset2">
    <%= page_header do %>
      <h1>
        <% if @status.user.avatar.attached? %>
          <%= image_tag(@status.user.avatar.variant(:thumb), alt: @status.user.full_name, class: 'img-circle') %>
        <% else %>
          <%= avatar_profile_link @status.user, {}, class: 'img-circle' %>
        <% end %>
        <%= @status.user.full_name %>
        <small><%= time_ago_in_words(@status.created_at) + " ago" %></small>
      </h1>
    <% end %>

    <h2>
      <%= @status.content %>
    </h2>
    <% if @status.document&.attachment&.attached? %>
      <%= image_tag(@status.document.attachment.variant(:large), class: "img-polaroid") %>
    <% end %>

    <hr />
    <div class="meta">
      <%= link_to 'Back', statuses_path %>
      <% if signed_in? && @status.user == current_user %>
        |
        <%= link_to "Edit", edit_status_path(@status) %> | 
        <%= link_to "Delete", @status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
      <% end %>
    </div>
  </div>
</div>