config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions],
    controllers: { omniauth_callbacks: 'omniauth_callbacks',
                   registrations: 'registrations'}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

  # root :to => 'high_voltage/pages#show', :id => 'home'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  get '/:id', to: 'profiles#show', as: :profile

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :album
  belongs_to :user

  validates_presence_of :album_id
  has_one_attached :asset do |attachable|
    attachable.variant :thumb,   resize_to_fill: [80, 80]
    attachable.variant :small,   resize_to_limit: [260, 180]
    attachable.variant :medium,  resize_to_limit: [300, 200]
    attachable.variant :large,   resize_to_limit: [800, 800]
  end
  validates :asset, attached: true, on: :create
  validates :asset, content_type: /\Aimage\/.*\Z/

  def to_s
    caption? ? caption : "Picture"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :update, :edit, :destroy]
  before_action :find_user
  before_action :find_album
  before_action :find_picture, only: [:edit, :update, :show, :destroy]
  before_action :ensure_proper_user, only: [:create, :new, :update, :edit, :destroy]
  before_action :add_breadcrumbs

  def index
    @pictures = @album.pictures.all.includes(:user)

    respond_to do |format|
      format.html
      format.json { render json: @pictures}
    end
  end

  def show
    @picture = @album.pictures.find(params[:id])
    add_breadcrumb @picture, album_picture_path(@album, @picture)

    respond_to do |format|
      format.html
      format.json { render json: @pictures}
    end
  end

  def new
    @picture = @album.pictures.new

    respond_to do |format|
      format.html
      format.json { render json: @pictures}
    end
  end

  def edit
  end

  def create
    @picture = @album.pictures.new(picture_params)

    respond_to do |format|
      if @picture.save
        current_user.create_activity @picture, 'created'
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        current_user.create_activity @picture, 'updated'
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      current_user.create_activity @picture, 'deleted'
      format.html { redirect_to album_pictures_url(@album), notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def url_options
    { profile_name: params[:profile_name] }.merge(super)
  end

  private
  def ensure_proper_user
    if current_user != @user
      flash[:error] = "You don't have permission to do that."
      redirect_to album_pictures_path
    end
  end

  def add_breadcrumbs
    add_breadcrumb @user.first_name, profile_path(@user)
    add_breadcrumb "Albums", albums_path
    add_breadcrumb "Pictures", album_pictures_path(@album)
  end

  def find_user
    @user = User.find_by(profile_name: params[:profile_name])
  end

  def find_album
    if signed_in? && current_user.profile_name == params[:profile_name]
      @album = current_user.albums.find(params[:album_id])
    else
      @album = @user.albums.find(params[:album_id])
    end
  end

  def find_picture
    @picture = @album.pictures.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:album_id, :user_id, :caption, :description, :asset)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def can_edit_picture?(picture)
    signed_in? && current_user == picture.user
  end
end

app/views/pictures/_form.html.erb
<%= simple_form_for([@album, @picture], html: { class: 'form-horizontal' }) do |f| %>
<%= f.error_notification %>

<div class="form-group">
  <label for="asset" class="col-sm-2 control-label">Asset</label>
  <div class="col-sm-10">
    <%= f.input :asset, label: false, as: :file %>
  </div>
</div>

<%= bootstrap_active_storage_picture f, :asset %>

<div class="form-group">
  <label for="caption" class="col-sm-2 control-label">Caption</label>
  <div class="col-sm-10">
    <%= f.input :caption, label: false , input_html: { class: 'input-xxlarge' } %>
  </div>
</div>

<div class="form-group">
  <label for="description" class="col-sm-2 control-label">Description</label>
  <div class="col-sm-10">
    <%= f.input :description, label: false , input_html: { class: 'input-xxlarge', rows: 4 }  %>
  </div>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/pictures/edit.html.erb
<%= page_header do %>
	<h1>Editing picture</h1>
<% end %>

<%= render 'form' %>

<br>
<%= link_to 'Show', album_picture_path(@album, @picture) %> |
<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/index.html.erb
<%= page_header do %>
	<% if signed_in? && current_user == @user %>
		<%= link_to 'Add Picture', new_album_picture_path(current_user, @album), class: 'btn pull-right btn-success' %>
		<h1><%= @album.title %></h1>
	<% end %>
<% end %>

<div class="row">
<% @pictures.each do |picture| %>
	<div class="col-xs-6 col-md-3">
		<div class="thumbnail">
			<%= link_to image_tag(picture.asset.variant(:small)), album_picture_path(@user, @album, picture) %><br />
			<div class="caption">
				<% if picture.caption? %><%= picture.caption %><br /><% end %>
				<%= link_to "View full size", album_picture_path(@user, @album, picture) %>
				<% if can_edit_picture?(picture) %>
					| <%= link_to "Edit", edit_album_picture_path(@album, picture) %>
					| <%= link_to "Delete", album_picture_path(@album, picture), method: :delete, data: { confirm: "Are you sure?" } %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>
</div>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/show.html.erb
<%= page_header do %>
	<h1>Viewing Picture</h1>
<% end %>

<%= image_tag(@picture.asset.variant(:large), alt: @picture.caption, class: "img-polaroid") %>

<br />

<h3><%= @picture.caption %></h3>
<p><%= @picture.description %></p>

<%= link_to 'Edit', edit_album_picture_path(@album, @picture), class: "btn btn-default btn-group" %>
<%= link_to 'Album', album_pictures_path(@album), class: "btn btn-default btn-group"  %>