config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions],
    controllers: { omniauth_callbacks: 'omniauth_callbacks',
                   registrations: 'registrations'}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

  # root :to => 'high_voltage/pages#show', :id => 'home'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  get '/:id', to: 'profiles#show', as: :profile

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Media</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top " role="navigation">
		<div class="container-fluid">
			<% if user_signed_in? %>
				<%= link_to "Site Name", activities_path, class: "navbar-brand" %>					
			<% else %>
				<%= link_to "Site Name", root_path, class: "navbar-brand" %>
			<% end %>
			<div class="navbar">
				<ul class="nav nav-pills navbar-left">
					<li><%= link_to "All Statuses", statuses_path %> </li>
					<% if user_signed_in? %>
						<li id="activity-feed"><%= link_to "Activity Feed", activities_path %></li>
					<% end %>
				</ul>
				<ul class="nav nav-pills navbar-right">
					<% if user_signed_in?%>
            <% if current_user.is_admin? %>
              <li><%= link_to 'Admin', admin_dashboard_path%></li>
            <% end %>
						<li><%= link_to 'Albums', albums_path(current_user) %></li>
						<li><%= link_to 'Friends', user_friendships_path %></li>
						<li><%= link_to current_user.full_name, edit_user_registration_path(@user) %></li>
						<li><%= link_to "Log Out", logout_path  %></li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "About", page_path('about') %></li>
						<li><%= link_to "Blog", blog_articles_path %></li>
						<li><%= link_to "Log In", login_path %></li>
					<% end %>
				</ul>
			</div>   
		</div>
	</nav>	
	
	<div class="container">
		<%= render_breadcrumbs %>
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">x</button>
				<%= message %>
			</div>
		<% end %>
		
		<%= yield %>
	</div>
</body>

<script id="activities-template" type="text/x-handlebars-template">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
		Activity Feed <span class="badge">{{count}}</span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
		{{#each activities}}
			{{activityLink}}
		{{/each}}
	<li role="presentation" class="divider"></li>
	<li><a href="{{activityFeedLink}}">Activity Feed</a></li>
	</ul>
</script>	
	
</html>